
-- // user: {
-- //     username: username,
-- //     passw: password,
-- // }
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    passw VARCHAR(100) NOT NULL
);

-- // inventories: {
-- //     user_id: user_id,
-- //     sku: sku,
-- //     quantity: quantity, 
-- //     description: description, 
-- //     location: location,
-- //     date_entered: date
-- // }
CREATE TABLE inventories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    sku TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    inv_description TEXT,
    inv_location TEXT,
    date_entered TEXT NOT NULL 
);

-- // suppliers: {
-- //     user_id: user_id,
-- //     company: companyName,
-- //     contact: contactName,
-- //     phone: supplierPhoneNumber,
-- //     email: supplierEmail,
-- //     address: supplierAddress
-- // }
CREATE TABLE suppliers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    company TEXT NOT NULL,
    contact TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    sup_address TEXT NOT NULL
);

-- // customers: {
-- //     user_id: user_id,
-- //     company: companyName,
-- //     contact: contactName,
-- //     phone: customerPhone,
-- //     email: customerEmail,
-- //     bill_address: customerBillAddress,
-- //     ship_address: customerShipAddress
-- // },
CREATE TABLE customers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    company TEXT NOT NULL,
    contact TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    bill_address TEXT NOT NULL,
    ship_address TEXT NOT NULL
);

-- // order: {
-- //     user_id: user_id,
-- //     company: customerCompanyName, 
-- //     sku: sku,
-- //     quantity: quantity,
-- //     description: description,
-- //     order: orderPO,
-- //     date_entered: date
-- // }
-- need to add a column for supplier orders
CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    company TEXT NOT NULL, 
    sku TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    inv_description TEXT,
    cust_order TEXT,
    sup_order TEXT,
    date_entered TEXT
);

-- // skus: {
-- //     user_id: user_id,
-- //     sku: sku,
-- //     description: description, 
-- //     date_entered: date
-- // }
CREATE TABLE skus (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    sku TEXT NOT NULL,
    inv_description TEXT NOT NULL,
    date_entered TEXT NOT NULL
);